version: 0.1

phases:
  install:
    commands:
      - printenv
      - echo Installing npm packages ... ${CODEBUILD_BUILD_ID}
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/**/*
  discard-paths: no
